"""
control_unit.py — Single-Cycle Control Unit
Single-Cycle Processor | Intel Semester Project

Decodes the 32-bit instruction's opcode and function field to produce
all datapath control signals for one clock cycle.

Instruction Format (R-type, 32-bit):
  [31:26]  opcode  (6 bits) — always 000000 for R-type
  [25:21]  rs      (5 bits) — source register 1
  [20:16]  rt      (5 bits) — source register 2
  [15:11]  rd      (5 bits) — destination register
  [10:06]  shamt   (5 bits) — shift amount (unused = 00000)
  [05:00]  funct   (6 bits) — selects ALU operation and NOT behavior

Function Field Encodings:
  0b100100  (0x24)  — AND         →  ALU_op=AND, InvertA=0
  0b100101  (0x25)  — OR          →  ALU_op=OR,  InvertA=0
  0b100110  (0x26)  — AND w/ NOT  →  ALU_op=AND, InvertA=1  (encodes ~A & B)

Key Design Decision:
  NOT is implemented entirely via the InvertA signal — NOT is NOT
  a separate opcode. The funct field encodes whether input A should
  be inverted before the AND gate, satisfying the requirement that
  inversion is encoded in the function field, not the opcode.
"""

from dataclasses import dataclass

# ── Opcode constants ───────────────────────────────────────────────────────────
OPCODE_RTYPE = 0b000000   # All supported instructions are R-type

# ── Function field constants ───────────────────────────────────────────────────
FUNCT_AND    = 0b100100   # 0x24  Standard AND
FUNCT_OR     = 0b100101   # 0x25  Standard OR
FUNCT_ANDINV = 0b100110   # 0x26  AND with input A inversion (NOT via control)

# ── ALU op constants (must match alu.py) ───────────────────────────────────────
ALU_OP_AND = 0b00
ALU_OP_OR  = 0b01


@dataclass
class ControlSignals:
    """
    Complete bundle of control signals generated by the Control Unit.

    These signals wire into every functional unit of the datapath
    and are valid for the entire clock cycle (single-cycle model).
    """
    reg_write: bool   # RegWrite  — 1: write ALU result to rd
    alu_op:    int    # ALUop     — 00: AND,  01: OR
    invert_a:  bool   # InvertA   — 1: bitwise-invert ALU input A before op
    op_name:   str    # Debug label for trace output


class ControlUnit:
    """
    Combinational control unit — no state, pure decode logic.

    Input:  opcode (6 bits) + funct (6 bits) from instruction register
    Output: ControlSignals dataclass

    Control Signal Table:
        Instruction | funct    | RegWrite | ALUop | InvertA
        ────────────┼──────────┼──────────┼───────┼────────
        AND         | 100100   |    1     |  00   |   0
        OR          | 100101   |    1     |  01   |   0
        ANDINV      | 100110   |    1     |  00   |   1    ← implements NOT
    """

    def decode(self, opcode: int, funct: int) -> ControlSignals:
        """
        Decode instruction fields and return datapath control signals.

        Args:
            opcode: 6-bit opcode field [31:26]
            funct:  6-bit function field [5:0]

        Returns:
            ControlSignals for this instruction

        Raises:
            ValueError if opcode or funct is unsupported
        """
        # ── Opcode check — only R-type (000000) supported ─────────────────────
        if opcode != OPCODE_RTYPE:
            raise ValueError(
                f"Unsupported opcode: {opcode:06b} ({opcode:#04x}). "
                f"Only R-type (000000) is implemented."
            )

        # ── Funct-field decode — differentiates AND / OR / ANDINV ─────────────
        if funct == FUNCT_AND:
            return ControlSignals(
                reg_write = True,
                alu_op    = ALU_OP_AND,
                invert_a  = False,       # Standard AND: A & B
                op_name   = "AND",
            )

        elif funct == FUNCT_ANDINV:
            # ANDINV: encodes NOT in the funct field, NOT as a separate opcode.
            # Control unit asserts InvertA → ALU receives ~A as first operand.
            # Result: (~A) & B  →  used for (~C) & D
            return ControlSignals(
                reg_write = True,
                alu_op    = ALU_OP_AND,
                invert_a  = True,        # Assert: invert input A before AND
                op_name   = "ANDINV",
            )

        elif funct == FUNCT_OR:
            return ControlSignals(
                reg_write = True,
                alu_op    = ALU_OP_OR,
                invert_a  = False,       # Standard OR: A | B
                op_name   = "OR",
            )

        else:
            raise ValueError(
                f"Unsupported funct field: {funct:06b} ({funct:#04x}). "
                f"Valid: AND=0x24, OR=0x25, ANDINV=0x26"
            )
